# hello:
#     path: /hello-world/{name}
#     controller: App\Controller\DefaultController::hello


home:
    path: /home
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: /hello-world
        permanent: true  